name: Build and Push Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - main
    labels:
      - 'CI:Build'

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t dzivdzi/go-ethereum:${{ github.sha }} .
          docker tag dzivdzi/go-ethereum:${{ github.sha }} dzivdzi/go-ethereum:latest

      - name: Push the Docker image
        run: |
          docker push dzivdzi/go-ethereum:${{ github.sha }}
          docker push dzivdzi/go-ethereum:latest